Shopping/Areas/Admin/Controllers/FeatureController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Shopping.Core.Interface;
using Shopping.Core.ViewModels;
using Shopping.Database.Model;

namespace Shopping.Areas.Admin.Controllers;

[Area("Admin")]
public class FeatureController : Controller
{
    IFeature _feature;
    public FeatureController(IFeature feature)
    {
        _feature = feature;
    }
    public async Task<IActionResult> Index()
    {
        #region GetAllFeatures
        //for getting All Features Model

        ViewBag.FeatureGroups = (await _feature.GetFeatureGroups()).OrderBy(f => f.GroupName);
        //ViewBag.FeatureSections = (await _feature.GetFeatureSections()).OrderBy(f => f.FeatureGroup.GroupName);
        //ViewBag.Features = (await _feature.GetFeatures()).OrderBy(f => f.FeatureSection.SectionName);

        #endregion

        return await Task.FromResult(View());
    }

    public async Task<IActionResult> FeaturesChart()
    {
        #region FEATURES CHART
        //for getting FeaturesChart
        var featureGroups = (await _feature.GetFeatureGroups()).OrderBy(f => f.GroupName);
        var featureSections = (await _feature.GetFeatureSections()).OrderBy(f => f.FeatureGroup.GroupName);
        var features = (await _feature.GetFeatures()).OrderBy(f => f.FeatureSection.SectionName);

        FeaturesChartViewModel featuresChart = new FeaturesChartViewModel()
        {
            FeatureGroups = featureGroups,
            FeatureSections = featureSections,
            Features = features,
        };
        #endregion
        return await Task.FromResult(View(featuresChart));
    }

    //////////////// FEATURE GROUP START ////////////////

    public async Task<IActionResult> GetFeatureGroups()
    {
        var feature = (await _feature.GetFeatureGroups()).OrderBy(f => f.GroupName);
        return await Task.FromResult(View(feature));
    }

    //public async Task<IActionResult> GetFeatureSectionsByFeatureGroup(int Id)//id==FeatureGroupId
    //{
    //    var feature = (await _feature.RelatedFeatureSections(Id)).OrderBy(f => f.SectionName);
    //    return await Task.FromResult(View(feature));
    //}
    public async Task<IActionResult> AddFeatureGroup()
    {
        //just for getting FeaturesGroup
        ViewBag.FeatureGroups = (await _feature.GetFeatureGroups()).OrderBy(f => f.GroupName);

        #region FEATURES CHART
        //for getting FeaturesChart
        var featureGroups = (await _feature.GetFeatureGroups()).OrderBy(f => f.GroupName);
        var featureSections = (await _feature.GetFeatureSections()).OrderBy(f => f.FeatureGroup.GroupName);
        var features = (await _feature.GetFeatures()).OrderBy(f => f.FeatureSection.SectionName);
        FeaturesChartViewModel featuresChart = new FeaturesChartViewModel()
        {
            FeatureGroups = featureGroups,
            FeatureSections = featureSections,
            Features = features,
        };
        ViewBag.AllFeatures = featuresChart;
        #endregion
        return await Task.FromResult(View());
    }

    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> AddFeatureGroup(FeatureGroup featureGroup)
    {
        if (ModelState.IsValid)
        {
            if (await _feature.AddFeatureGroup(featureGroup))
            {
                return RedirectToAction(nameof(AddFeatureGroup));
            }
        }
        return RedirectToAction(nameof(AddFeatureGroup));
    }

    public async Task<IActionResult> EditFeatureGroup(int Id)
    {
        var feature = await _feature.GetFeatureGroup(Id);
        if (feature != null)
        {
            return await Task.FromResult(View(feature));
        }
        return RedirectToAction(nameof(Index));
    }

    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> EditFeatureGroup(FeatureGroup featureGroup)
    {
        if (ModelState.IsValid)
        {
            if (await _feature.EditFeatureGroup(featureGroup))
            {
                return RedirectToAction(nameof(GetFeatureGroups));
            }
        }
        TempData["Message"] = false;
        return RedirectToAction(nameof(GetFeatureGroups));
    }

    public async Task<IActionResult> FeatureGroupDetails(int Id/*, string? GroupName*/) //Id==FeatureGroupId
    {
        //if (Id != null)
        //{
        var feature = await _feature.GetFeatureGroup(Id);
        if (feature != null)
        {
            ViewBag.FeatureGroups = (await _feature.GetFeatureGroups()).OrderBy(f => f.GroupName);
            ViewBag.RelatedFeatureSections = await _feature.RelatedFeatureSections(feature.Id);
            return await Task.FromResult(View(feature));
        }
        //}
        //if (GroupName != null)
        //{
        //    var feature = await _feature.GetFeatureGroup(Id: null, GroupName: GroupName);
        //    if (feature != null)
        //    {
        //        ViewBag.RelatedFeatureSections = await _feature.RelatedFeatureSections(feature.Id);
        //        return await Task.FromResult(View(feature));
        //    }
        //}

        return RedirectToAction(nameof(Index));
    }

    public async Task<IActionResult> FeatureGroupDelete(int Id) //Id==FeatureGroupId
    {
        var feature = await _feature.GetFeatureGroup(Id);
        if (feature != null)
        {
            return PartialView(feature);
        }
        return RedirectToAction(nameof(Index));
    }
    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> FeatureGroupDelete(FeatureGroup featureGroup)
    {
        if (await _feature.DeleteFeatureGroup(featureGroup.Id))
        {
            return RedirectToAction(nameof(GetFeatureGroups));
        }
        return RedirectToAction(nameof(GetFeatureGroups));
    }

    //////////////// FEATURE GROUP END ////////////////


    //////////////// FEATURE SECTION START ////////////////

    public async Task<IActionResult> GetFeatureSections()
    {
        var feature = (await _feature.GetFeatureSections()).OrderBy(f => f.FeatureGroup.GroupName);
        return await Task.FromResult(View(feature));
    }


    public async Task<IActionResult> AddFeatureSection()
    {
        //for Selecte GroupFeature To Add FeatureSection
        ViewBag.FeatureGroupId = new SelectList((await _feature.GetFeatureGroups()).OrderBy(f => f.GroupName), "Id", "GroupName");

        //just for getting FeatureSections
        ViewBag.FeatureSections = (await _feature.GetFeatureSections()).OrderBy(f => f.FeatureGroup.GroupName);

        #region FEATURES CHART
        //for getting FeaturesChart
        var featureGroups = (await _feature.GetFeatureGroups()).OrderBy(f => f.GroupName);
        var featureSections = (await _feature.GetFeatureSections()).OrderBy(f => f.FeatureGroup.GroupName);
        var features = (await _feature.GetFeatures()).OrderBy(f => f.FeatureSection.SectionName);
        FeaturesChartViewModel featuresChart = new FeaturesChartViewModel()
        {
            FeatureGroups = featureGroups,
            FeatureSections = featureSections,
            Features = features,
        };
        ViewBag.AllFeatures = featuresChart;
        #endregion

        return await Task.FromResult(View());
    }

    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> AddFeatureSection(FeatureSection featureSection)
    {
        if (ModelState.IsValid)
        {
            if (await _feature.AddFeatureSection(featureSection))
            {
                return RedirectToAction(nameof(AddFeatureSection));
            }
        }
        return RedirectToAction(nameof(AddFeatureSection));
    }

    public async Task<IActionResult> EditFeatureSection(int Id)//Id==FeatureSectionId
    {
        var feature = await _feature.GetFeatureSection(Id);
        if (feature != null)
        {
            ViewBag.FeatureGroupId = new SelectList((await _feature.GetFeatureGroups()).OrderBy(f => f.GroupName), "Id", "GroupName");
            return await Task.FromResult(View(feature));
        }
        return RedirectToAction(nameof(Index));
    }
    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> EditFeatureSection(FeatureSection featureSection)
    {
        if (ModelState.IsValid)
        {
            if (await _feature.EditFeatureSection(featureSection))
            {
                return RedirectToAction(nameof(GetFeatureSections));
            }
        }
        return RedirectToAction(nameof(GetFeatureSections));
    }


    public async Task<IActionResult> FeatureSectionDetails(int Id) //Id==FeatureSectionId
    {
        var feature = await _feature.GetFeatureSection(Id);
        if (feature != null)
        {
            ViewBag.RelatedFeatures = await _feature.RelatedFeature(Id);
            return await Task.FromResult(View(feature));
        }
        return RedirectToAction(nameof(Index));
    }


    public async Task<IActionResult> FeatureSectionDelete(int Id)//Id==FeatureSectionId
    {
        var feature = await _feature.GetFeatureSection(Id);
        if (feature != null)
        {
            return PartialView(feature);
        }
        return RedirectToAction(nameof(Index));
    }
    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> FeatureSectionDelete(FeatureSection featureSection)
    {
        if (await _feature.DeleteFeatureSection(featureSection.Id))
        {
            return RedirectToAction(nameof(GetFeatureSections));
        }
        return RedirectToAction(nameof(GetFeatureSections));
    }

    //////////////// FEATURE SECTION END ////////////////

    //////////////// FEATURE START ////////////////
    public async Task<IActionResult> GetFeatures()
    {
        var feature = (await _feature.GetFeatures()).OrderBy(f => f.FeatureSection.SectionName);
        return await Task.FromResult(View(feature));
    }
    public async Task<IActionResult> AddFeature()
    {

Shopping/Areas/Admin/Views/Feature/AddFeatureGroup.cshtml
@model Shopping.Database.Model.FeatureGroup

@{
    ViewData["Title"] = "AddFeatureGroup";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}


<h1>افزودن گروه ثبت ویژگی</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-area="Admin" asp-controller="Feature" asp-action="AddFeatureGroup">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="GroupName" class="control-label"></label>
                <input asp-for="GroupName" class="form-control" />
                <span asp-validation-for="GroupName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


<hr style="opacity: 20" class="text-danger " />
<partial name="FeatureGroupsPartial.cshtml" model="@ViewBag.FeatureGroups" />
<hr style="opacity: 20" class="text-danger " />
<partial name="FeaturesChartPartial.cshtml" model="@ViewBag.AllFeatures" />
<hr style="opacity: 20" class="text-danger " />


<div>
    <a asp-action="Index">Back to List</a>
</div>

Shopping/Areas/Admin/Views/Feature/FeatureDelete.cshtml
@model Shopping.Database.Model.Feature

<div>
    <h5>نام قسمت ویژگی : @Model.FeatureSection.SectionName</h5>
    <h5>نام عنوان ویژگی : @Model.Title</h5>
    <hr />
    <h4 class="text-danger text-center">آیا حذف  میکنید؟</h4>
    <form asp-area="Admin" asp-controller="Feature" asp-action="FeatureDelete" class="text-center">
        <input asp-for="Id" hidden />
        <button class="btn btn-success">بله <span class="bi bi-check2-circle fa-lg"></span></button>
        <a asp-area="Admin" asp-controller="Feature" asp-action="GetFeatures" class="btn btn-danger">خیر <span class=" bi bi-x-circle fa-lg"></span></a>
    </form>
</div>

Shopping/Areas/Admin/Views/Feature/FeatureDetails.cshtml
@model Shopping.Database.Model.Feature

@{
    ViewData["Title"] = "FeatureDetails";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>FeatureDetails</h1>

<div>
    <h4>Feature</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FeatureSection)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FeatureSection.SectionName)
        </dd>
    </dl>
</div>
<div>
    <a asp-area="Admin" asp-controller="Feature" asp-action="EditFeature" asp-route-id="@Model?.Id" class="btn btn-warning"><span class="bi bi bi-pen"></span></a> |
    <a asp-action="Index">Back to List</a>
</div>
<hr style="opacity: 20" class="text-danger " />
<partial name="FeaturesPartial.cshtml" model="ViewBag.RelatedFeature" />

Shopping/Areas/Admin/Views/Feature/FeatureGroupDelete.cshtml
@model Shopping.Database.Model.FeatureGroup

<div>
    <h4>نام گروه ویژگی : @Model.GroupName</h4>
    <hr />
    <h4 class="text-danger text-center">آیا حذف  میکنید؟</h4>
    <form asp-area="Admin" asp-controller="Feature" asp-action="FeatureGroupDelete" class="text-center">
        <input asp-for="Id" hidden />
        <button class="btn btn-success">بله <span class="bi bi-check2-circle fa-lg"></span></button>
        <a asp-area="Admin" asp-controller="Feature" asp-action="GetFeatureGroups" class="btn btn-danger">خیر <span class=" bi bi-x-circle fa-lg"></span></a>
    </form>
</div>



@* <h3>Are you sure you want to delete this?</h3>
<div>
    <h4>FeatureGroup</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GroupName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GroupName)
        </dd>
    </dl>
    
    <form asp-action="FeatureGroupDelete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div> *@

Shopping/Areas/Admin/Views/Feature/FeatureGroupDetails.cshtml
@model Shopping.Database.Model.FeatureGroup

@{
    ViewData["Title"] = "FeatureGroupDetails";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>FeatureGroupDetails</h1>

<div>
    <h4>FeatureGroup</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.GroupName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.GroupName)
        </dd>
    </dl>
</div>
<hr />
<div>
    <a asp-area="Admin" asp-controller="Feature" asp-action="EditFeatureGroup" asp-route-id="@Model?.Id" class="btn btn-warning"><span class="bi bi bi-pen"></span></a> |
    <a asp-action="Index">Back to List</a>
</div>
<hr style="opacity: 20" class="text-danger " />
<partial name="FeatureGroupsPartial.cshtml" model="@ViewBag.FeatureGroups" />

Shopping/Areas/Admin/Views/Feature/FeatureSectionDelete.cshtml
@model Shopping.Database.Model.FeatureSection

<div>
    <h5>نام گروه ویژگی : @Model.FeatureGroup.GroupName</h5>
    <h5>نام قسمت ویژگی : @Model.SectionName</h5>
    <hr />
    <h4 class="text-danger text-center">آیا حذف  میکنید؟</h4>
    <form asp-area="Admin" asp-controller="Feature" asp-action="FeatureSectionDelete" class="text-center">
        <input asp-for="Id" hidden />
        <button class="btn btn-success">بله <span class="bi bi-check2-circle fa-lg"></span></button>
        <a asp-area="Admin" asp-controller="Feature" asp-action="GetFeatureSections" class="btn btn-danger">خیر <span class=" bi bi-x-circle fa-lg"></span></a>
    </form>
</div>

Shopping/Areas/Admin/Views/Feature/FeatureSectionDetails.cshtml
@model Shopping.Database.Model.FeatureSection

@{
    ViewData["Title"] = "FeatureSectionDetails";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>FeatureSectionDetails</h1>

<div>
    <h4>FeatureSection</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SectionName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SectionName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FeatureGroup)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FeatureGroup.GroupName)
        </dd>
    </dl>
</div>
<div>
    <a asp-area="Admin" asp-controller="Feature" asp-action="EditFeatureSection" asp-route-id="@Model?.Id" class="btn btn-warning"><span class="bi bi bi-pen"></span></a> |
    <a asp-action="Index">Back to List</a>
</div>

<hr style="opacity: 20" class="text-danger " />
<partial name="FeaturesPartial.cshtml" model="ViewBag.RelatedFeatures" />

Shopping/Areas/Admin/Views/Feature/FeaturesChart.cshtml
@model Shopping.Core.ViewModels.FeaturesChartViewModel

@{
    ViewData["Title"] = "FeaturesChart";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>FeaturesChart</h1>
<hr />

@{
    if (Model.FeatureGroups.Count() > 0)
    {
        <h1> نمودار ویژگی ها</h1>

        <table class="table">
            <tbody>
                @{
                    int ii = 1;
                    int iii = 1;
                    int iiii = 1;
                    var _featureGroup = Model.FeatureGroups.ToList();
                    for (int i = 0; i < _featureGroup.Count(); i++)
                    {
                    //<a asp-area="Admin" asp-controller="Feature" asp-action="FeatureGroupDetails" asp-route-GroupName="@_groupDistinct[i]" class="btn btn-info"> @_groupDistinct[i]</a>
                        <a asp-area="Admin" asp-controller="Feature" asp-action="FeatureGroupDetails" asp-route-Id="@_featureGroup[i].Id" class="btn btn-danger me-1 mt-1"><span>(@ii)</span>@_featureGroup[i].GroupName</a>
                        ii++;

                        @foreach (var _featureSections in Model.FeatureSections.Where(f => f.FeatureGroup.GroupName == _featureGroup[i].GroupName))
                        {
                        //<a class="btn btn-warning me-1 m-1">@sections.SectionName</a>
                            <a asp-area="Admin" asp-controller="Feature" asp-action="FeatureSectionDetails" asp-route-Id="@_featureSections.Id" class="btn btn-warning me-1 mt-1"><span>(@iii)</span>@_featureSections.SectionName</a>
                            iii++;

                            @foreach (var _features in _featureSections.Features.Where(f => f.FeatureSection.SectionName == _featureSections.SectionName))
                            {
                            //<a class="btn btn-danger">@item.Title</a>
                                <a asp-area="Admin" asp-controller="Feature" asp-action="FeatureDetails" asp-route-Id="@_features.Id" class="btn btn-success me-1 mt-1"><span>(@iiii)</span>@_features.Title</a>
                                iiii++;
                            }
                            iiii = 1;
                        }
                        iii = 1;
                    }
                }
            </tbody>
        </table>
    }
    else
    {
        <h1 class="text-danger">نمودار ویژگی ها خالی می باشد</h1>
    }
}

Shopping/Areas/Admin/Views/Feature/FeaturesChartPartial.cshtml
@model Shopping.Core.ViewModels.FeaturesChartViewModel


@* @{
    ViewData["Title"] = "FeaturesChart";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
} *@

@{
    if (Model.FeatureGroups.Count()>0)
    {
        <h1> نمودار ویژگی ها</h1>

        <table class="table">
            <tbody>
                @{
                    int ii = 1;
                    int iii = 1;
                    int iiii = 1;
                    var _featureGroup = Model.FeatureGroups.ToList();
                    for (int i = 0; i < _featureGroup.Count(); i++)
                    {
                    //<a asp-area="Admin" asp-controller="Feature" asp-action="FeatureGroupDetails" asp-route-GroupName="@_groupDistinct[i]" class="btn btn-info"> @_groupDistinct[i]</a>
                        <a asp-area="Admin" asp-controller="Feature" asp-action="FeatureGroupDetails" asp-route-Id="@_featureGroup[i].Id" class="btn btn-danger me-1 mt-1"><span>(@ii)</span>@_featureGroup[i].GroupName</a>
                        ii++;

                        @foreach (var _featureSections in Model.FeatureSections.Where(f => f.FeatureGroup.GroupName == _featureGroup[i].GroupName))
                        {
                        //<a class="btn btn-warning me-1 m-1">@sections.SectionName</a>
                            <a asp-area="Admin" asp-controller="Feature" asp-action="FeatureSectionDetails" asp-route-Id="@_featureSections.Id" class="btn btn-warning me-1 mt-1"><span>(@iii)</span>@_featureSections.SectionName</a>
                            iii++;

                            @foreach (var _features in _featureSections.Features.Where(f => f.FeatureSection.SectionName == _featureSections.SectionName))
                            {
                            //<a class="btn btn-danger">@item.Title</a>
                                <a asp-area="Admin" asp-controller="Feature" asp-action="FeatureDetails" asp-route-Id="@_features.Id" class="btn btn-success me-1 mt-1"><span>(@iiii)</span>@_features.Title</a>
                                iiii++;
                            }
                            iiii = 1;
                        }
                        iii = 1;
                    }
                }
            </tbody>
        </table>
    }
    else
    {
        <h1 class="text-danger">نمودار ویژگی ها خالی می باشد</h1>
    }
}

Shopping/Areas/Admin/Views/Feature/GetFeatureGroups.cshtml
@model IEnumerable<Shopping.Database.Model.FeatureGroup>

@{
    ViewData["Title"] = "FeatureGroupsPartial";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}


<h1> گروه ویژگی</h1>

@{
    if (Model.Count()>0)
    {
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.GroupName)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.GroupName)
                        </td>
                        <td>
                            <a asp-area="Admin" asp-controller="Feature" asp-action="EditFeatureGroup" asp-route-id="@item.Id" class="btn btn-warning"><span class="bi bi bi-pen"></span></a> |
                            <a asp-area="Admin" asp-controller="Feature" asp-action="FeatureGroupDetails" asp-route-id="@item.Id" class="btn btn-info"><span class="bi bi-info-square"></span></a> |
                            <a data-bs-toggle="modal" data-bs-target="#exampleModal" onclick="DeleteFeatureGroup('@(item.Id)')" class="btn btn-danger"><span class="bi bi-trash"></span></a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <h1 class="text-danger">فعلا گروه ویژگی وجود ندارد</h1>
    }
}



<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div id="modalBody" class="modal-body">
                ...
            </div>
            @*<div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Save changes</button>
            </div>*@
        </div>
    </div>
</div>



<script>
    const myModal = document.getElementById('myModal')
    const myInput = document.getElementById('myInput')

    myModal.addEventListener('shown.bs.modal', () => {
        myInput.focus()
    })
    function DeleteFeatureGroup(FeatureGroupId) {
        $.ajax({
            url: '/Admin/Feature/FeatureGroupDelete',
            type: 'get',
            data: {/*controller parameter*/  id: FeatureGroupId /*send parameter*/ },
            success: (result) => {
                document.getElementById('modalBody').innerHTML = result;
            }
        })
    }

</script>

Shopping/Areas/Admin/Views/Feature/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Index</h1>
<a asp-area="Admin" asp-controller="Feature" asp-action="AddFeatureGroup" class="btn btn-success"><span class="bi bi-patch-plus"> افزودن گروه ثبت ویژگی</span></a> \\\\\\\\\\\\
<a asp-area="Admin" asp-controller="Feature" asp-action="AddFeatureSection" class="btn btn-success"><span class="bi bi-patch-plus"> افزودن قسمت ثبت ویژگی</span></a> \\\\\\\\\\\\
<a asp-area="Admin" asp-controller="Feature" asp-action="AddFeature" class="btn btn-success"><span class="bi bi-patch-plus"> افزودن ویژگی</span></a> \\\\\\\\\\\\


<hr style="opacity: 20" class="text-danger" />
@* <a asp-area="admin" asp-controller="feature" asp-action="addallfeatures" class="btn btn-outline-success">افرودن ویژگی ها</a>//////////// *@
<a asp-area="Admin" asp-controller="Feature" asp-action="GetFeatureGroups" class="btn btn-warning">FeatureGroups</a> ////////////
<a asp-area="Admin" asp-controller="Feature" asp-action="GetFeatureSections" class="btn btn-info">FeatureSections</a> ////////////
<a asp-area="Admin" asp-controller="Feature" asp-action="GetFeatures" class="btn btn-danger">Features</a> ////////////
<a asp-area="Admin" asp-controller="Feature" asp-action="FeaturesChart" class="btn btn-dark">FeaturesChart</a> ////////////
@* <hr style="opacity: 20" class="text-danger" />
<partial name="FeatureGroupsPartial.cshtml" model="@ViewBag.FeatureGroups" /> *@
@* <hr style="opacity: 20" class="text-danger" />
<partial name="FeatureSectionsPartial.cshtml" model="@ViewBag.FeatureSections" />
<hr style="opacity: 20" class="text-danger " />
<partial name="FeaturesPartial.cshtml" model="@ViewBag.Features" /> *@