Shopping/Areas/Admin/Controllers/ProductClassificationController.cs
using Microsoft.AspNetCore.Mvc;
using Shopping.Core.Interface;
using Shopping.Core.ViewModels;
using Shopping.Database.Model;
using System.Drawing.Drawing2D;

namespace Shopping.Areas.Admin.Controllers;

[Area("Admin")]
public class ProductClassificationController : Controller
{
    string imgPath = "wwwroot/Images/ProductClassification";

    IBrand _brand;
    ICommodity _commodity;
    IClassification _classification;
    public ProductClassificationController(IBrand brand,ICommodity commodity,IClassification classification)
    {
        _brand = brand;
        _commodity = commodity;
        _classification = classification;
    }
    public async Task<IActionResult> Index()
    {
        var classifications = await _classification.GetProductClassifications();
        return View(classifications);
    }

    public async Task<IActionResult> CreateClassification()
    {
        ViewBag.ClassificationId=Guid.NewGuid();
        return await Task.FromResult(View());
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> CreateClassification(ProductClassification classification, IFormFile ClsfLogo)
    {
        if (ModelState.IsValid)
        {
            if (await _classification.AddClassification(classification,ClsfLogo))
            {
                return RedirectToAction(nameof(Index));
            }
            ViewBag.ClassificationId = Guid.NewGuid();
            ModelState.AddModelError("GroupEnName", "خطا در ثبت برند");
        }
        ViewBag.ClassificationId = Guid.NewGuid();
        return await Task.FromResult(View(classification));
    }

    public async Task<IActionResult> ClassificationDetails(Guid ClassificationId)//id= classificationId
    {
        var classification = await _classification.GetProductClassification(ClassificationId);
        ViewBag.RelatedCommodity = (await _commodity.GetClassificationCommodities(ClassificationId)).Take(5)/*.OrderByDescending(c=>c.RegisterDate)*/;  
        //به ترتیب جدید ترین ها محصول ها را گرفتم
        //اینجا باید مثلا 5 تا محصول بفرستم که دکمه نمایش بیشتر رو دز بره اون محصولایی که تو این دسته بندی هستن رو نمایش بده
        //بعد باید همه محصولات رئ نشون بدم اونایی که عدم نمایش هستن رو روش قرمز بنویسم نه عدم نمایش 
        //اونایی که عکس ندارن هم باید بگم که عکسی برای محصول وجود ندارد
        return await Task.FromResult(View(classification));
    }




    public async Task<IActionResult> EditClassification(Guid ClassificationId)//id=brandId
    {
        var classification = await _classification.GetProductClassification(ClassificationId);
        if (classification != null)
        {
            EditClassificationViewModel viewModel = new EditClassificationViewModel()
            {
                Id = classification.Id,
                GroupEnName = classification.GroupEnName,
                GroupFaName = classification.GroupFaName,
                GroupImg = classification.GroupImg,
                GroupDes = classification.GroupDes,
                NotShow = classification.NotShow,
            };
            var previousImg = viewModel.GroupImg;
            TempData["Img"] = previousImg.ToString();
            return await Task.FromResult(View(viewModel));
        }
        return RedirectToAction(nameof(Index));
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> EditClassification(EditClassificationViewModel classification, IFormFile? File)
    {
        if (ModelState.IsValid)
        {
            if (await _classification.EditClassification(classification, File))
            {
                if (File != null)
                {
                    //for deleting previous image
                    var previousimg = (TempData["Img"]).ToString();
                    string ExitingFile = Path.Combine(imgPath, previousimg);
                    System.IO.File.Delete(ExitingFile);
                    //end deleting previous image
                }
                return RedirectToAction(nameof(ClassificationDetails), new { ClassificationId = classification.Id });
            }
        }
        return await Task.FromResult(View(classification));
    }




    //public async Task<IActionResult> EditClassificationTitle(Guid Id)//id==classificationId 
    //{
    //    var classification=await _classification.GetProductClassification(Id);
    //    if (classification!=null)
    //    {
    //        EditClassificationViewModel viewModel = new EditClassificationViewModel()
    //        {
    //            Id = classification.Id,
    //            GroupEnName = classification.GroupEnName,
    //            GroupFaName = classification.GroupFaName,
    //            GroupImg = classification.GroupImg,
    //            GroupDes = classification.GroupDes,
    //            NotShow = classification.NotShow,
    //        };
    //        return await Task.FromResult(View(viewModel));
    //    }
    //    return RedirectToAction(nameof(Index));

    //}
    //[HttpPost]
    //[ValidateAntiForgeryToken]
    //public async Task<IActionResult> EditClassificationTitle(EditClassificationViewModel viewModel)
    //{
    //    if (ModelState.IsValid)
    //    {
    //        if (await _classification.EditClassification(viewModel))
    //        {
    //            return RedirectToAction(nameof(ClassificationDetails), new { Id = viewModel.Id });
    //        }
    //        return await Task.FromResult( View(viewModel));
    //    }
    //    return await Task.FromResult(View(viewModel));
    //}


    //public async Task<IActionResult> EditClassificationImg(Guid Id)//id==classificationId 
    //{
    //    var classification = await _classification.GetProductClassification(Id);
    //    if (classification!=null) 
    //    {
    //        EditClassificationViewModel viewModel = new EditClassificationViewModel()
    //        {
    //            Id = classification.Id,
    //            GroupEnName = classification.GroupEnName,
    //            GroupFaName = classification.GroupFaName,
    //            GroupImg = classification.GroupImg,
    //            GroupDes = classification.GroupDes,
    //            NotShow = classification.NotShow,
    //        };

    //        var previousImg = viewModel.GroupImg;
    //        TempData["Img"] = previousImg.ToString();
    //        return await Task.FromResult(View(viewModel));
    //    }
    //    return RedirectToAction(nameof(Index));

    //}
    //[HttpPost]
    //[ValidateAntiForgeryToken]
    //public async Task<IActionResult> EditClassificationImg(EditClassificationViewModel viewModel,IFormFile ClassificationImg)
    //{
    //    if (ModelState.IsValid)
    //    {
    //        if (await _classification.EditClassificationImg(viewModel,ClassificationImg))
    //        {
    //            //for deleting previous image
    //            var previousimg = (TempData["Img"]).ToString();
    //            string ExitingFile = Path.Combine(imgPath, previousimg);
    //            System.IO.File.Delete(ExitingFile);
    //            //end deleting previous image

    //            ViewBag.RelatedCommodity = (await _commodity.GetClassificationCommodities(viewModel.Id)).Take(5);
    //            return RedirectToAction(nameof(ClassificationDetails), new { Id = viewModel.Id });
    //        }
    //        return await Task.FromResult(View(viewModel));
    //    }
    //    ModelState.AddModelError("GroupEnName", " ویرایش امکان پذیر نمی باشد");
    //    return await Task.FromResult(View(viewModel));
    //}


    public async Task<IActionResult> DeleteClassification(Guid Id)
    {
        var classsification = await _classification.GetProductClassification(Id);
        if (classsification!=null)
        {
            return PartialView(classsification);
        }
        return RedirectToAction(nameof(Index));
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteClassification(ProductClassification classification)
    {
        var Previousimg = (await _classification.GetProductClassification(classification.Id)).GroupImg;
        if (await _classification.DeleteClassification(classification.Id))
        {
            string ExitingFile = Path.Combine(imgPath, Previousimg);
            System.IO.File.Delete(ExitingFile);

            return RedirectToAction(nameof(Index));
        }
        return RedirectToAction(nameof(Index));
    }
}

Shopping/Areas/Admin/Views/ProductClassification/ClassificationDetails.cshtml
@model Shopping.Database.Model.ProductClassification

@{
    ViewData["Title"] = "ClassificationDetails";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>ClassificationDetails</h1>

<div>
    <h4>ProductClassification</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GroupEnName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GroupEnName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GroupFaName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GroupFaName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GroupImg)
        </dt>
        <dd class = "col-sm-10">
            @* @Html.DisplayFor(model => model.GroupImg) *@
            <img src="~/Images/ProductClassification/@Model.GroupImg" width="100"/>
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GroupDes)
        </dt>
        <dd class = "col-sm-10">

            @{
                if (Model.GroupDes == null)
                {
                    <h6><span class="fa fa-times text-danger"></span>توضیحاتی وجود ندارد<span class="fa fa-times text-danger"></span></h6>
                }
                @Html.DisplayFor(model => model.GroupDes)
            }
            
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NotShow)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NotShow)
        </dd>
    </dl>
</div>

<partial name="~/Areas/Admin/Views/Commodity/CommodityPartial.cshtml" model="@ViewBag.RelatedCommodity" />

<div>
    <a asp-area="Admin" asp-controller="ProductClassification" asp-action="EditClassification" asp-route-ClassificationId="@Model.Id" class="btn btn-warning"><span class="bi bi bi-pen"></span></a> |
    <a class="btn btn-dark">نمایش محصولات بیشتر از این دسته</a> |
    <a asp-area="Admin" asp-controller="ProductClassification" asp-action="Index">Back to List</a>
</div>

Shopping/Areas/Admin/Views/ProductClassification/CreateClassification.cshtml
@model Shopping.Database.Model.ProductClassification

@{
    ViewData["Title"] = "CreateClassification";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>CreateClassification</h1>

<h4>ProductClassification</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-area="Admin" asp-controller="ProductClassification" asp-action="CreateClassification" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" value="@ViewBag.ClassificationId" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GroupEnName" class="control-label"></label>
                <input asp-for="GroupEnName" class="form-control" />
                <span asp-validation-for="GroupEnName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GroupFaName" class="control-label"></label>
                <input asp-for="GroupFaName" class="form-control" />
                <span asp-validation-for="GroupFaName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GroupImg" class="control-label"></label>
                <br />
                <input type="file" name="ClsfLogo" onchange="ImgPreview(this)" accept=".jpg,.png" />
                <img id="Product-preview" src="" width="256" />
                <input asp-for="GroupImg" id="img-name" class="form-control" />
                <span asp-validation-for="GroupImg" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GroupDes" class="control-label"></label>
                <input asp-for="GroupDes" class="form-control" />
                <span asp-validation-for="GroupDes" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="NotShow" /> @Html.DisplayNameFor(model => model.NotShow)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

<script>
    function ImgPreview(input) {
        if (input.files && input.files[0]) {
            let reader = new FileReader();
            reader.onload = (e) => {
                let img = document.getElementById('Product-preview');
                img.setAttribute('src', e.target.result);

                document.getElementById('img-name').value = input.files[0].name;
            }

            reader.readAsDataURL(input.files[0]);
        }
    }
</script>

Shopping/Areas/Admin/Views/ProductClassification/DeleteClassification.cshtml
@model Shopping.Database.Model.ProductClassification

<div>
    <img src="~/Images/ProductClassification/@Model.GroupImg" width="200" />
    <h4>BrandName : @Model.GroupEnName</h4>
    <h5>نام برند : @Model.GroupFaName</h5>
    <hr />
    <h4 class="text-danger text-center">آیا حذف  میکنید؟</h4>
    <form asp-area="Admin" asp-controller="ProductClassification" asp-action="DeleteClassification" class="text-center">
        <input asp-for="Id" hidden />
        <button class="btn btn-success">بله <span class="bi bi-check2-circle fa-lg"></span></button>
        <a asp-area="Admin" asp-controller="ProductClassification" asp-action="Index" class="btn btn-danger">خیر <span class=" bi bi-x-circle fa-lg"></span></a>
    </form>
</div>

Shopping/Areas/Admin/Views/ProductClassification/EditClassification.cshtml
@model Shopping.Core.ViewModels.EditClassificationViewModel

@{
    ViewData["Title"] = "EditClassification";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>EditClassification</h1>

<h4>ProductClassification</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-area="Admin" asp-controller="ProductClassification" asp-action="EditClassification" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="GroupEnName" class="control-label"></label>
                <input asp-for="GroupEnName" class="form-control" />
                <span asp-validation-for="GroupEnName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GroupFaName" class="control-label"></label>
                <input asp-for="GroupFaName" class="form-control" />
                <span asp-validation-for="GroupFaName" class="text-danger"></span>
            </div>
           @*  <div class="form-group">
                <label asp-for="GroupImg" class="control-label"></label>
                <input asp-for="GroupImg" class="form-control" />
                <span asp-validation-for="GroupImg" class="text-danger"></span>
            </div> *@
            <div class="form-group">
                <br />
                <input type="file" name="File" onchange="ImgPreview(this)" accept=".jpg,.png" />
                <img id="Classification-preview" src="~/Images/ProductClassification/@Model.GroupImg" width="256" />
                <label asp-for="GroupImg" class="control-label"></label>
                <input asp-for="GroupImg" value="@Model.GroupImg" id="img-name" class="form-control" />
                <span asp-validation-for="GroupImg" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GroupDes" class="control-label"></label>
                <input asp-for="GroupDes" class="form-control" />
                <span asp-validation-for="GroupDes" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="NotShow" /> @Html.DisplayNameFor(model => model.NotShow)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

<script>
    function ImgPreview(input) {
        if (input.files && input.files[0]) {
            let reader = new FileReader();
            reader.onload = (e) => {
                let img = document.getElementById('Classification-preview');
                img.setAttribute('src', e.target.result);

                document.getElementById('img-name').value = input.files[0].name;
            }

            reader.readAsDataURL(input.files[0]);
        }
    }
</script>

Shopping/Areas/Admin/Views/ProductClassification/EditClassificationImg.cshtml
@model Shopping.Core.ViewModels.EditClassificationViewModel

@{
    ViewData["Title"] = "EditClassificationImg";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>EditClassificationImg</h1>

<h4>ProductClassification</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-area="Admin" asp-controller="ProductClassification" asp-action="EditClassificationImg" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" readonly />

            <img src="~/Images/ProductClassification/@Model.GroupImg" width="250" class="rounded-3 bg-white">
            >>>>>>>
            <div class="form-group">
                <label asp-for="GroupEnName" class="control-label"></label>
                <input asp-for="GroupEnName" class="form-control" readonly />
                <span asp-validation-for="GroupEnName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GroupFaName" class="control-label"></label>
                <input asp-for="GroupFaName" class="form-control" readonly />
                <span asp-validation-for="GroupFaName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <br />
                <input type="file" name="ClassificationImg" onchange="ImgPreview(this)" accept=".jpg,.png" />
                <img id="Brand-preview" src="" width="256" />
                <label asp-for="GroupImg" class="control-label"></label>
                <input asp-for="GroupImg" value="@Model.GroupImg" id="img-name" class="form-control" />
                <span asp-validation-for="GroupImg" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GroupDes" class="control-label"></label>
                <input type="text" asp-for="GroupDes" class="form-control" readonly />
                <span asp-validation-for="GroupDes" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="NotShow" hidden readonly/> @Html.DisplayNameFor(model => model.NotShow)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

<script>
    function ImgPreview(input) {
        if (input.files && input.files[0]) {
            let reader = new FileReader();
            reader.onload = (e) => {
                let img = document.getElementById('Brand-preview');
                img.setAttribute('src', e.target.result);

                document.getElementById('img-name').value = input.files[0].name;
            }

            reader.readAsDataURL(input.files[0]);
        }
    }
</script>

Shopping/Areas/Admin/Views/ProductClassification/Index.cshtml
@model IEnumerable<Shopping.Database.Model.ProductClassification>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-area="Admin" asp-controller="ProductClassification" asp-action="CreateClassification" class="btn btn-success"><span class="bi bi-patch-plus"> Create</span></a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.GroupEnName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GroupFaName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GroupImg)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GroupDes)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NotShow)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.GroupEnName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.GroupFaName)
                </td>
                <td>
                    @*  @Html.DisplayFor(modelItem => item.GroupImg) *@
                    <img src="~/Images/ProductClassification/@item.GroupImg" width="50">
                </td>
                <td>
                    @* if group des==null write هیچ توضیحاتی وجود ندارد *@
                    @{
                        if (item.GroupDes == null)
                        {
                            <h6><span class="fa fa-times text-danger"></span>توضیحاتی وجود ندارد<span class="fa fa-times text-danger"></span></h6>
                        }
                        @Html.DisplayFor(modelItem => item.GroupDes)
                    }
                    
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NotShow)
                </td>
                <td>
                    <a asp-area="Admin" asp-controller="ProductClassification" asp-action="EditClassification" asp-route-ClassificationId="@item.Id" class="btn btn-warning"><span class="bi bi bi-pen"></span></a> |
                    <a asp-area="Admin" asp-controller="ProductClassification" asp-action="ClassificationDetails" asp-route-ClassificationId="@item.Id" class="btn btn-info"><span class="bi bi-info-square"></span></a> |
                    <a data-bs-toggle="modal" data-bs-target="#exampleModal" onclick="DeleteClassification('@(item.Id)')" class="btn btn-danger"><span class="fa fa-trash-o"></span></a> |
                </td>
            </tr>
        }
    </tbody>
</table>



<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title text-center fs-5" id="exampleModalLabel">حذف کردن طبقه بندی</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div id="modalBody" class="modal-body">
                ...
            </div>
            @*<div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Save changes</button>
            </div>*@
        </div>
    </div>
</div>



<script>
    const myModal = document.getElementById('myModal')
    const myInput = document.getElementById('myInput')

    myModal.addEventListener('shown.bs.modal', () => {
        myInput.focus()
    })
    function DeleteClassification(ClassificationId) {
        $.ajax({
            url: '/admin/ProductClassification/DeleteClassification',
            type: 'get',
            data: {/*controller parameter*/  id: ClassificationId /*send parameter*/ },
            success: (result) => {
                document.getElementById('modalBody').innerHTML = result;
            }
        })
    }

</script>