Shopping/Areas/Admin/Controllers/CommodityController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Shopping.Core.Interface;
using Shopping.Core.ViewModels;
using Shopping.Database.Model;
using System.Drawing.Drawing2D;
using System.Security.Policy;
using System.Text.RegularExpressions;

namespace Shopping.Areas.Admin.Controllers;

[Area("Admin")]
public class CommodityController : Controller
{
    string CommodityImgPath = "wwwroot/Images/Commodity";
    string CommodityAlbumImgPath = "wwwroot/Images/Commodity/CommodityAlbum";

    ICommodity _commodity;
    IBrand _brand;
    IClassification _classification;
    IFeature _feature;
    public CommodityController(ICommodity commodity, IBrand brand, IClassification classification, IFeature feature)
    {
        _commodity = commodity;
        _brand = brand;
        _classification = classification;
        _feature = feature;
    }
    public async Task<IActionResult> Index()
    {
        var commodities = (await _commodity.GetCommodities(/*ClassificationId:Guid.Empty,*/)).OrderBy(f => f.RegisterDate);
        return View(commodities);
    }


    //public async Task<IActionResult> GetCommodities()
    //{
    //    //var Id1 = TempData["Id1"];
    //    //var Id2 = TempData["Id2"];
    //    //var Id3 = TempData["Id3"];
    //    //var Id4 = TempData["Id4"];
    //    var commodities = await _commodity.GetCommodities(/*ClassificationId:Guid.Empty,*/);

    //    CompareViewModel compareView = new CompareViewModel()
    //    {
    //        Commodities = commodities,
    //    };


    //    return await Task.FromResult( View(commodities));
    //}


    public async Task<IActionResult> AddNewCommodity()
    {
        ViewBag.BrandCount = (await _brand.GetBrands()).Count();
        ViewBag.ClassificationCount = (await _classification.GetProductClassifications()).Count();
        ViewBag.BrandId = new SelectList(await _brand.GetBrands(), "Id", "BrandEnName");
        ViewBag.ClassificationId = new SelectList(await _classification.GetProductClassifications(), "Id", "GroupEnName");
        ViewBag.CommodityId = Guid.NewGuid();
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> AddNewCommodity(Commodity commodity, IFormFile CommodityImg)
    {
        if (ModelState.IsValid)
        {
            if (await _commodity.AddCommodity(commodity, CommodityImg))
            {
                return RedirectToAction(nameof(Index));
            }
            ModelState.AddModelError("ProductFaName", "خطا در ثبت محصول");
        }
        ViewBag.BrandId = new SelectList(await _brand.GetBrands(), "Id", "BrandEnName");
        ViewBag.ClassificationId = new SelectList(await _classification.GetProductClassifications(), "Id", "GroupEnName");
        ViewBag.CommodityId = Guid.NewGuid();
        ViewBag.BrandCount = (await _brand.GetBrands()).Count();
        return View(commodity);
    }




    public async Task<IActionResult> AddCommodityAlbum(Guid Id)
    {
        ViewBag.Message = TempData["Message"];
        var commodity = await _commodity.GetCommodity(Id);

        var commodityAlbum = await _commodity.GetCommodityAlbums(commodity.Id);

        if (commodityAlbum != null)
        {
            ViewBag.Album = commodityAlbum;
        }

        ViewBag.Commodity = commodity;
        ViewBag.CommodityId = commodity.Id;
        ViewBag.Id = Guid.NewGuid();
        TempData["CommodityId"] = Id;
        return await Task.FromResult(View());
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> AddCommodityAlbum(CommodityAlbum album, IFormFile CommodityImg)
    {
        if (ModelState.IsValid)
        {
            if (await _commodity.AddAlbum(album, CommodityImg))
            {
                return RedirectToAction(nameof(AddCommodityAlbum), new { id = album.CommodityId });
            }
            ModelState.AddModelError("CommodityImg", "خطا در ثبت محصول");
        }

        TempData["Message"] = "دوباره امتحان کنید";
        return RedirectToAction(nameof(AddCommodityAlbum), new { id = album.CommodityId });

        //ModelState.AddModelError("CommodityImg", "خطا در ثبت محصول");
        //ViewBag.Album = await _commodity.GetCommodityAlbums(album.CommodityId);
        //ViewBag.Id = Guid.NewGuid();

    }

    public async Task<IActionResult> RemoveCommodityAlbum(Guid Id)
    {
        var commodity = await _commodity.GetCommodityAlbum(Id);
        if (commodity == null)
        {
            return RedirectToAction(nameof(Index));
        }
        return PartialView(commodity);

    }


    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> RemoveCommodityAlbum(CommodityAlbum commodityAlbum)
    {
        var previousimg = (await _commodity.GetCommodityAlbum(commodityAlbum.Id)).CommodityImg;
        if (await _commodity.DeleteCommodityAlbum(commodityAlbum.Id))
        {
            string ExitingFile = Path.Combine(CommodityAlbumImgPath, previousimg);
            System.IO.File.Delete(ExitingFile);

            return RedirectToAction(nameof(AddCommodityAlbum), new { Id = TempData["CommodityId"] });
        }
        return RedirectToAction(nameof(AddCommodityAlbum), new { Id = TempData["CommodityId"] });
    }


    public async Task<IActionResult> CommodityDetails(Guid CommodityId) 
    {
        var commodity = await _commodity.GetCommodity(CommodityId);
        if (commodity == null)
        {
            return RedirectToAction(nameof(Index));
        }
        ViewBag.Album = await _commodity.GetCommodityAlbums(CommodityId);
        return await Task.FromResult(View(commodity));
    }


    public async Task<IActionResult> DeleteCommodity(Guid Id)
    {
        var commodity = await _commodity.GetCommodity(Id);
        //ViewBag.CommodityAlbum = (await _commodity.GetCommodityAlbums(Id)).Take(4);
        if (commodity != null)
        {
            return PartialView(commodity);
        }
        return RedirectToAction(nameof(Index));
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteCommodity(Commodity commodity)
    {
        var commoDetails = await _commodity.GetCommodity(commodity.Id);
        if (commoDetails != null)
        {
            if (await _commodity.DeleteCommodity(commodity.Id))
            {
                return RedirectToAction(nameof(Index));
            }
            return await Task.FromResult(View(commoDetails));
        }
        return await Task.FromResult(View(commoDetails));
    }



    //public async Task<IActionResult> EditCommodity(Guid Id)//id==commodityId
    //{
    //    var commodity = await _commodity.GetCommodity(Id);
    //    ViewBag.BrandId = new SelectList(await _brand.GetBrands(), "Id", "BrandEnName");
    //    ViewBag.ClassificationId = new SelectList(await _classification.GetProductClassifications(), "Id", "GroupEnName");
    //    if (commodity != null)
    //    {
    //        return await Task.FromResult(View(commodity));
    //    }
    //    return RedirectToAction(nameof(Index));
    //}

    //[HttpPost]
    //[ValidateAntiForgeryToken]
    //public async Task<IActionResult> EditCommodity(Commodity commodity)
    //{

    //    if (ModelState.IsValid)
    //    {
    //        if (await _commodity.EditCommodity(commodity))
    //        {
    //            return RedirectToAction(nameof(CommodityDetails), new { Id = commodity.Id });
    //        }
    //        ViewBag.BrandId = new SelectList(await _brand.GetBrands(), "Id", "BrandEnName");
    //        ViewBag.ClassificationId = new SelectList(await _classification.GetProductClassifications(), "Id", "GroupEnName");
    //        return await Task.FromResult(View(commodity));
    //    }
    //    ViewBag.BrandId = new SelectList(await _brand.GetBrands(), "Id", "BrandEnName");
    //    ViewBag.ClassificationId = new SelectList(await _classification.GetProductClassifications(), "Id", "GroupEnName");
    //    return await Task.FromResult(View(commodity));
    //}

    //public async Task<IActionResult> EditCommodityImg(Guid CommodityId)
    //{
    //    var commodity = await _commodity.GetCommodity(CommodityId);
    //    if (commodity != null)
    //    {
    //        EditCommodityViewModel viewModel = new EditCommodityViewModel()
    //        {
    //            Id = commodity.Id,
    //            BrandId = commodity.BrandId,
    //            GroupId = commodity.GroupId,
    //            ProductFaName = commodity.ProductFaName,
    //            ProductEnName = commodity.ProductEnName,
    //            ProductImg = commodity.ProductImg,
    //            Price = commodity.Price,
    //            Discount = commodity.Discount,
    //            Inventory = commodity.Inventory,
    //            Introduction = commodity.Introduction,
    //            NotShow = commodity.NotShow,
    //            RegisterDate = commodity.RegisterDate,
    //            UpdateDate = commodity.UpdateDate,
    //        };

    //        var previousImg = viewModel.ProductImg;
    //        TempData["Img"] = previousImg.ToString();
    //        return await Task.FromResult(View(viewModel));
    //    }
    //    return RedirectToAction(nameof(Index));
    //}

    //[HttpPost]
    //[ValidateAntiForgeryToken]
    //public async Task<IActionResult> EditCommodityImg(EditCommodityViewModel viewModel, IFormFile CommodityImg)
    //{
    //    if (ModelState.IsValid && CommodityImg != null)
    //    {
    //        if (await _commodity.EditCommodityImg(viewModel, CommodityImg))
    //        {
    //            //for deleting previous image
    //            var previousimg = (TempData["Img"]).ToString();
    //            string ExitingFile = Path.Combine(CommodityImgPath, previousimg);
    //            System.IO.File.Delete(ExitingFile);
    //            //end deleting previous image

    //            return RedirectToAction(nameof(CommodityDetails), new { id = viewModel.Id });
    //        }

Shopping/Areas/Admin/Views/Commodity/AddCommodityAlbum.cshtml
@model Shopping.Database.Model.CommodityAlbum

@{
    ViewData["Title"] = "AddCommodityAlbum";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

@{
    if (ViewBag.Message != null)
    {
        TempData["msg"] = "<script>alert('دوباره امتحان کنید');</script>";
        @Html.Raw(TempData["msg"])

        <h1 class="text-danger"><span class="fa fa-times text-danger"></span>@ViewBag.Message<span class="fa fa-times text-danger"></span></h1>
    }
}

<partial name="CommodityDetailPartial.cshtml" model="@ViewBag.Commodity" />
<hr />
@{
    if (ViewBag.Album != null)
    {
        <partial name="DeleteAlbumPartial.cshtml" model="@ViewBag.Album" />
    }
    else
    {
        <h1 class="text-danger">عکسی برای این محصول وجود ندارد</h1>
    }
}

<hr />


<div class="row">
    <div class="col-md-4">
        <form asp-area="Admin" asp-controller="Commodity" asp-action="AddCommodityAlbum" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group" hidden>
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" value="@ViewBag.Id" class="form-control" readonly hidden />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group" hidden>
                <label asp-for="CommodityId" class="control-label"></label>
                <input asp-for="CommodityId" class="form-control" value="@ViewBag.CommodityId" readonly hidden/>
            </div>
            <div class="form-group">
                <label asp-for="CommodityImg" class="control-label"></label>
                <br />
                <input type="file" name="CommodityImg" onchange="ImgPreview(this)" accept=".jpg,.png" />
                <img id="Product-preview" src="" width="256" />
                <input asp-for="CommodityImg" id="img-name" class="form-control"  readonly hidden/>
                <span asp-validation-for="CommodityImg" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>



<div>
    <a asp-action="Index">Back to List</a>
</div>

<script>
    function ImgPreview(input) {
        if (input.files && input.files[0]) {
            let reader = new FileReader();
            reader.onload = (e) => {
                let img = document.getElementById('Product-preview');
                img.setAttribute('src', e.target.result);

                document.getElementById('img-name').value = input.files[0].name;
            }

            reader.readAsDataURL(input.files[0]);
        }
    }
</script>

Shopping/Areas/Admin/Views/Commodity/AddNewCommodity.cshtml
@model Shopping.Database.Model.Commodity

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Create</h1>

<h4>Commodity</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-area="Admin" asp-controller="Commodity" asp-action="AddNewCommodity" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label" hidden></label>
                <input asp-for="Id" value="@ViewBag.CommodityId" class="form-control" readonly hidden/>
                <span asp-validation-for="Id" class="text-danger" hidden></span>
            </div>
            <div class="form-group">
                @{
                    if (ViewBag.BrandCount < 1)
                    {
                        <label asp-for="BrandId" class="control-label"></label>
                        <input asp-for="BrandId" class="form-control bg-danger" placeholder="گروهی وجود ندارد" readonly/>
                    }
                    else
                    {
                        <label asp-for="BrandId" class="control-label"></label>
                        <select asp-for="BrandId" class="form-control" asp-items="ViewBag.BrandId"><option selected disabled hidden> گروه را انتخاب کنید </option></select>

                    }
                }
                
            </div>
            
            <div class="form-group">
                @{
                    if (ViewBag.ClassificationCount < 1)
                    {
                        <label asp-for="GroupId" class="control-label"></label>
                        <input asp-for="GroupId" class="form-control bg-danger" placeholder="گروهی وجود ندارد" readonly />
                    }
                    else
                    {
                        <label asp-for="GroupId" class="control-label"></label>
                        <select asp-for="GroupId" class="form-control" asp-items="ViewBag.ClassificationId"><option selected disabled hidden> گروه را انتخاب کنید </option></select>

                    }
                }

            </div>

            <div class="form-group">
                <label asp-for="ProductFaName" class="control-label"></label>
                <input asp-for="ProductFaName" class="form-control" placeholder="نام کالا به فارسی"/>
                <span asp-validation-for="ProductFaName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductEnName" class="control-label"></label>
                <input asp-for="ProductEnName" class="form-control" placeholder="نام کالا به انگلیسی"/>
                <span asp-validation-for="ProductEnName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductImg" class="control-label"></label>
                <br />
                <input type="file" name="CommodityImg" onchange="ImgPreview(this)" accept=".jpg,.png" />
                <img id="Product-preview" src="" width="256" />
                <input asp-for="ProductImg" id="img-name" class="form-control" readonly hidden />
                <span asp-validation-for="ProductImg" class="text-danger"></span>
            </div>
            <div class="form-group">

                <label asp-for="Price" class="control-label"></label>
                <span asp-validation-for="Price" class="text-danger"></span>
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text">تومان</span>
                    </div>
                    <input asp-for="Price" min="0" class="form-control" aria-label="Amount (to the nearest dollar)" placeholder="0" />
                </div>

            </div>
            <div class="form-group">
                <label asp-for="Discount" class="control-label"></label>
                <input asp-for="Discount" value="0" placeholder="0" min="0" max="99" class="form-control" />
                <span asp-validation-for="Discount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Inventory" class="control-label"></label>
                <input asp-for="Inventory" min="0" class="form-control" placeholder="تعداد موجودی کالا را وارد نمایید"/>
                <span asp-validation-for="Inventory" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Introduction" class="control-label"></label>
                <input asp-for="Introduction" class="form-control" />
                <span asp-validation-for="Introduction" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="NotShow" /> @Html.DisplayNameFor(model => model.NotShow)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="RegisterDate" class="control-label" hidden></label>
                <input asp-for="RegisterDate" class="form-control" readonly hidden/>
                <span asp-validation-for="RegisterDate" class="text-danger" hidden></span>
            </div>
            <div class="form-group">
                <label asp-for="UpdateDate" class="control-label" hidden></label>
                <input asp-for="UpdateDate" class="form-control" readonly hidden />
                <span asp-validation-for="UpdateDate" class="text-danger" hidden></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

<script>
    function ImgPreview(input) {
        if (input.files && input.files[0]) {
            let reader = new FileReader();
            reader.onload = (e) => {
                let img = document.getElementById('Product-preview');
                img.setAttribute('src', e.target.result);

                document.getElementById('img-name').value = input.files[0].name;
            }

            reader.readAsDataURL(input.files[0]);
        }
    }
</script>

Shopping/Areas/Admin/Views/Commodity/CommodityAlbumPartial.cshtml
@model IEnumerable<Shopping.Database.Model.CommodityAlbum>

@{
    if (Model.Count() == 0)
    {
        <h1 class="text-danger">عکسی برای این محصول وجود ندارد</h1>
    }
    else
    {
        <table class="table">
            <thead>
                <tr>
                    @* <th>
            @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
            @Html.DisplayNameFor(model => model.CommodityId)
            </th> *@
                    <th>
                        @Html.DisplayNameFor(model => model.CommodityImg)
                    </th>
                    @* <th></th>*@
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        @*  <td>
            @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
            @Html.DisplayFor(modelItem => item.CommodityId)
            </td> *@
                        <td>
                            @* @Html.DisplayFor(modelItem => item.CommodityImg) *@
                            <img src="~/Images/commodity/@item.CommodityImg " width="210">
                        </td>

                        <td>
                            @* <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> | *@
                            @* <a asp-action="RemoveCommodityAlbum" asp-route-id="@item.Id">Delete</a>*@
                            <a data-bs-toggle="modal" data-bs-target="#exampleModal1" onclick="DeleteImg('@(item.Id)')" class="btn btn-danger"><span class="fa fa-trash-o"></span></a> |
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
}

<div class="modal fade" id="exampleModal1" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title text-center fs-5" id="exampleModalLabel">حذف کردن عکس</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div id="modalBody" class="modal-body">
                ...
            </div>
            @*<div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Save changes</button>
            </div>*@
        </div>
    </div>
</div>



<script>
    const myModal = document.getElementById('myModal')
    const myInput = document.getElementById('myInput')

    myModal.addEventListener('shown.bs.modal', () => {
        myInput.focus()
    })
    function DeleteImg(CommodityId) {
        $.ajax({
            url: '/admin/commodity/RemoveCommodityAlbum',
            type: 'get',
            data: {/*controller parameter*/  Id: CommodityId /*send parameter*/ },
            success: (result) => {
                document.getElementById('modalBody').innerHTML = result;
            }
        })
    }

</script>

Shopping/Areas/Admin/Views/Commodity/EditCommodity.cshtml
@model Shopping.Core.ViewModels.EditCommodityViewModel

@{
    ViewData["Title"] = "EditCommodity";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>EditCommodity</h1>

<h4>Commodity</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-area="Admin" asp-controller="Commodity" asp-action="EditCommodity" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="BrandId" class="control-label"></label>
                <select asp-for="BrandId" class="form-control" asp-items="ViewBag.BrandId"></select>
                <span asp-validation-for="BrandId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GroupId" class="control-label"></label>
                <select asp-for="GroupId" class="form-control" asp-items="ViewBag.ClassificationId"></select>
                <span asp-validation-for="GroupId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductFaName" class="control-label"></label>
                <input asp-for="ProductFaName" class="form-control" />
                <span asp-validation-for="ProductFaName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductEnName" class="control-label"></label>
                <input asp-for="ProductEnName" class="form-control" />
                <span asp-validation-for="ProductEnName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <br />
                <input type="file" name="CommodityImg" onchange="ImgPreview(this)" accept=".jpg,.png" />
                <img id="Commodity-preview" src="~/Images/Commodity/@Model.ProductImg" width="256" />
                <label asp-for="ProductImg" class="control-label"></label>
                <input asp-for="ProductImg" value="@Model.ProductImg" id="img-name" class="form-control" />
                <span asp-validation-for="ProductImg" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Discount" class="control-label"></label>
                <input asp-for="Discount" class="form-control" />
                <span asp-validation-for="Discount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Inventory" class="control-label"></label>
                <input asp-for="Inventory" class="form-control" />
                <span asp-validation-for="Inventory" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Introduction" class="control-label"></label>
                <input asp-for="Introduction" class="form-control" />
                <span asp-validation-for="Introduction" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="NotShow" /> @Html.DisplayNameFor(model => model.NotShow)
                </label>
            </div>
            <div class="form-group" >
                <label asp-for="RegisterDate" class="control-label" ></label>
                <input asp-for="RegisterDate" class="form-control" readonly />
                <span asp-validation-for="RegisterDate" class="text-danger" ></span>
            </div>
            <div class="form-group" >
                <label asp-for="UpdateDate" class="control-label" ></label>
                <input asp-for="UpdateDate" class="form-control" readonly/>
                <span asp-validation-for="UpdateDate" class="text-danger" ></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

<script>
    function ImgPreview(input) {
        if (input.files && input.files[0]) {
            let reader = new FileReader();
            reader.onload = (e) => {
                let img = document.getElementById('Commodity-preview');
                img.setAttribute('src', e.target.result);

                document.getElementById('img-name').value = input.files[0].name;
            }

            reader.readAsDataURL(input.files[0]);
        }
    }
</script>

Shopping/Areas/Admin/Views/Commodity/GetProduct.cshtml
@model Shopping.Database.Model.Commodity

<hr />
<div>
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductFaName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductFaName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductEnName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductEnName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Discount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Discount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Inventory)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Inventory)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Introduction)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Introduction)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NotShow)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NotShow)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RegisterDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RegisterDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpdateDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpdateDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Brand)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Brand.BrandEnName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Group)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Group.GroupEnName)
        </dd>
    </dl>
</div>


@{
    var DeleteId = Model.Id;
    var Id1 = TempData["Id1"];
    var Id2 = TempData["Id2"];
    var Id3 = TempData["Id3"];
    var Id4 = TempData["Id4"];

}
<a asp-area="Admin" asp-controller="Commodity" asp-action="CompareCommodities" asp-route-Id1="@Id1" asp-route-Id2="@Id2" asp-route-Id3="@Id3" asp-route-Id4="@Id4" asp-route-DeleteId="@Model.Id" class="btn btn-danger">حذف</a>