Shopping/Areas/Admin/Controllers/BrandController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Shopping.Core.Interface;
using Shopping.Core.ViewModels;
using Shopping.Database.Model;

namespace Shopping.Areas.Admin.Controllers;

[Area("admin")]
public class BrandController : Controller
{
    IBrand _brand;
    string imgPath = "wwwroot/Images/Brand";

    public BrandController(IBrand brand)
    {
        _brand = brand;
    }

    public async Task<IActionResult> Index()
    {
        var brands = (await _brand.GetBrands()).OrderBy(f => f.BrandEnName);
        return View(brands);
    }

    public async Task<IActionResult> CreateNewBrand()
    {
        ViewBag.BrandId = Guid.NewGuid();
        return await Task.FromResult(View());
    }


    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> CreateNewBrand(Brand brand, IFormFile brandLogo)
    {
        if (ModelState.IsValid)
        {
            if (await _brand.AddBrand(brand, brandLogo))
            {
                return RedirectToAction(nameof(Index));
            }
            ModelState.AddModelError("BrandEnName", "خطا در ثبت برند");
        }
        ViewBag.CommodityId = Guid.NewGuid();
        return await Task.FromResult(View(brand));
    }

    public async Task<IActionResult> BrandDetails(Guid BrandId)//id=brandId
    {
        var brand = await _brand.GetBrand(BrandId);
        if (brand != null)
        {
            return await Task.FromResult(View(brand));
        }
        return RedirectToAction(nameof(Index));
    }


    public async Task<IActionResult> EditBrand(Guid BrandId)//id=brandId
    {
        var brand = await _brand.GetBrand(BrandId);
        if (brand != null)
        {
            EditBrandViewModel viewModel = new EditBrandViewModel()
            {
                Id = brand.Id,
                BrandEnName = brand.BrandEnName,
                BrandFaName = brand.BrandFaName,
                BrandDes = brand.BrandDes,
                BrandImg = brand.BrandImg,
                NotShow = brand.NotShow,
            };
            var previousImg = viewModel.BrandImg;
            TempData["Img"] = previousImg.ToString();
            return await Task.FromResult(View(viewModel));
        }
        return RedirectToAction(nameof(Index));
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> EditBrand(EditBrandViewModel brand, IFormFile? File)
    {
        if (ModelState.IsValid)
        {
            if (await _brand.EditBrand(brand, File))
            {
                if (File != null)
                {
                    //for deleting previous image
                    var previousimg = (TempData["Img"]).ToString();
                    string ExitingFile = Path.Combine(imgPath, previousimg);
                    System.IO.File.Delete(ExitingFile);
                    //end deleting previous image
                }
                return RedirectToAction(nameof(BrandDetails), new { BrandId = brand.Id });
            }
        }
        return await Task.FromResult(View(brand));
    }



    //public async Task<IActionResult> EditBrandTitel(Guid Id)//id=brandId
    //{
    //    var brand = await _brand.GetBrand(Id);
    //    if (brand != null)
    //    {
    //        EditBrandViewModel viewModel = new EditBrandViewModel()
    //        {
    //            Id = brand.Id,
    //            BrandEnName = brand.BrandEnName,
    //            BrandFaName = brand.BrandFaName,
    //            BrandDes = brand.BrandDes,
    //            BrandImg = brand.BrandImg,
    //            NotShow = brand.NotShow,
    //        };
    //        return await Task.FromResult(View(viewModel));
    //    }
    //    return RedirectToAction(nameof(Index));
    //}

    //[HttpPost]
    //[ValidateAntiForgeryToken]
    //public async Task<IActionResult> EditBrandTitel(EditBrandViewModel viewModel)
    //{
    //    if (ModelState.IsValid)
    //    {
    //        if (await _brand.EditBrand(viewModel))
    //        {
    //            return RedirectToAction(nameof(BrandDetails), new { id = viewModel.Id });
    //        }
    //        return await Task.FromResult(View(viewModel));
    //    }
    //    return await Task.FromResult(View(viewModel));
    //}







    //public async Task<IActionResult> EditBrandImg(Guid Id)//id=brandId
    //{
    //    var brand = await _brand.GetBrand(Id);
    //    if (brand != null)
    //    {
    //        EditBrandViewModel viewModel = new EditBrandViewModel()
    //        {
    //            Id = brand.Id,
    //            BrandEnName = brand.BrandEnName,
    //            BrandFaName = brand.BrandFaName,
    //            BrandDes = brand.BrandDes,
    //            BrandImg = brand.BrandImg,
    //            NotShow = brand.NotShow,
    //        };

    //        var previousImg = viewModel.BrandImg;
    //        TempData["Img"] = previousImg.ToString();
    //        return await Task.FromResult(View(viewModel));
    //    }
    //    return RedirectToAction(nameof(Index));
    //}

    //[HttpPost]
    //[ValidateAntiForgeryToken]
    //public async Task<IActionResult> EditBrandImg(EditBrandViewModel viewModel, IFormFile BrandImg)
    //{
    //    if (ModelState.IsValid && BrandImg != null)
    //    {
    //        if (await _brand.EditBrandImg(viewModel, BrandImg))
    //        {
    //            //for deleting previous image
    //            var previousimg = (TempData["Img"]).ToString();
    //            string ExitingFile = Path.Combine(imgPath, previousimg);
    //            System.IO.File.Delete(ExitingFile);
    //            //end deleting previous image

    //            return RedirectToAction(nameof(BrandDetails), new { id = viewModel.Id });
    //        }
    //        return await Task.FromResult(View(viewModel));
    //    }
    //    return await Task.FromResult(View(viewModel));
    //}

    public async Task<IActionResult> DeleteBrand(Guid Id)//id==brandId
    {
        var brand = await _brand.GetBrand(Id);
        if (brand != null)
        {
            return PartialView(brand);
        }
        return RedirectToAction(nameof(Index));
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteBrand(Brand brand)
    {
        var Previousimg = (await _brand.GetBrand(brand.Id)).BrandImg;
        if (await _brand.DeleteBrand(brand.Id))
        {
            string ExitingFile = Path.Combine(imgPath, Previousimg);
            System.IO.File.Delete(ExitingFile);

            return RedirectToAction(nameof(Index));
        }
        return RedirectToAction(nameof(Index));
    }
}

Shopping/Areas/Admin/Views/Brand/BrandDetails.cshtml
@model Shopping.Database.Model.Brand

@{
    ViewData["Title"] = "BrandDetails";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>BrandDetails</h1>

<div>
    <h4>Brand</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BrandEnName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BrandEnName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BrandFaName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BrandFaName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BrandDes)
        </dt>
        <dd class = "col-sm-10">
            @{
                if (Model.BrandDes==null)
                {
                    <h6><span class="fa fa-times text-danger"></span>توضیحاتی وجود ندارد<span class="fa fa-times text-danger"></span></h6>
                }
                @Html.DisplayFor(model => model.BrandDes)
            }
            
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BrandImg)
        </dt>
        <dd class = "col-sm-10">
            @* @Html.DisplayFor(model => model.BrandImg) *@
            <img src="~/images/brand/@Model.BrandImg" width="500"/>
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NotShow)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NotShow)
        </dd>
    </dl>
</div>
<div>
    <a asp-area="Admin" asp-controller="Brand" asp-action="EditBrand" asp-route-BrandId="@Model?.Id" class="btn btn-warning"><span class="bi bi bi-pen"></span></a> |
    <a asp-action="Index">Back to List</a>
</div>

Shopping/Areas/Admin/Views/Brand/CreateBrand.cshtml
@model Shopping.Database.Model.Brand

@{
    ViewData["Title"] = "CreateBrand";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Create</h1>

<h4>Brand</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateBrand" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label" hidden></label>
                <input asp-for="Id" value="@ViewBag.BrandId" class="form-control" readonly hidden/>
                <span asp-validation-for="Id" class="text-danger" hidden></span>
            </div>
            <div class="form-group">
                <label asp-for="BrandEnName" class="control-label"></label>
                <input asp-for="BrandEnName" class="form-control" />
                <span asp-validation-for="BrandEnName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BrandFaName" class="control-label"></label>
                <input asp-for="BrandFaName" class="form-control" />
                <span asp-validation-for="BrandFaName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BrandDes" class="control-label"></label>
                <textarea asp-for="BrandDes" class="form-control" ></textarea>
                <span asp-validation-for="BrandDes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BrandImg" class="control-label"></label>
                <br />
                <input type="file" name="brandLogo" onchange="ImgPreview(this)" accept=".jpg,.png" />
                <img id="Product-preview" src="" width="256" />
                <input asp-for="BrandImg" id="img-name" class="form-control" />
                <span asp-validation-for="BrandImg" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="NotShow" /> @Html.DisplayNameFor(model => model.NotShow)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>


<script>
    function ImgPreview(input) {
        if (input.files && input.files[0]) {
            let reader = new FileReader();
            reader.onload = (e) => {
                let img = document.getElementById('Product-preview');
                img.setAttribute('src', e.target.result);

                document.getElementById('img-name').value = input.files[0].name;
            }

            reader.readAsDataURL(input.files[0]);
        }
    }
</script>

Shopping/Areas/Admin/Views/Brand/CreateNewBrand.cshtml
@model Shopping.Database.Model.Brand

@{
    ViewData["Title"] = "CreateBrand";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Create</h1>

<h4>Brand</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-area="Admin" asp-controller="Brand" asp-action="CreateNewBrand" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label" hidden></label>
                <input asp-for="Id" value="@ViewBag.BrandId" class="form-control" readonly hidden/>
                <span asp-validation-for="Id" class="text-danger" hidden></span>
            </div>
            <div class="form-group">
                <label asp-for="BrandEnName" class="control-label"></label>
                <input asp-for="BrandEnName" class="form-control" />
                <span asp-validation-for="BrandEnName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BrandFaName" class="control-label"></label>
                <input asp-for="BrandFaName" class="form-control" />
                <span asp-validation-for="BrandFaName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BrandDes" class="control-label"></label>
                <textarea asp-for="BrandDes" class="form-control" ></textarea>
                <span asp-validation-for="BrandDes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BrandImg" class="control-label"></label>
                <br />
                <input type="file" name="brandLogo" onchange="ImgPreview(this)" accept=".jpg,.png" />
                <img id="Product-preview" src="" width="256" />
                <input asp-for="BrandImg" id="img-name" class="form-control" />
                <span asp-validation-for="BrandImg" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="NotShow" /> @Html.DisplayNameFor(model => model.NotShow)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>


<script>
    function ImgPreview(input) {
        if (input.files && input.files[0]) {
            let reader = new FileReader();
            reader.onload = (e) => {
                let img = document.getElementById('Product-preview');
                img.setAttribute('src', e.target.result);

                document.getElementById('img-name').value = input.files[0].name;
            }

            reader.readAsDataURL(input.files[0]);
        }
    }
</script>

Shopping/Areas/Admin/Views/Brand/DeleteBrand.cshtml
@model Shopping.Database.Model.Brand

<div>
    <img src="~/Images/Brand/@Model.BrandImg"  width="200"/>
    <h4>BrandName : @Model.BrandEnName</h4>
    <h5>نام برند : @Model.BrandFaName</h5>
    <hr />
    <h4 class="text-danger text-center">آیا حذف  میکنید؟</h4>
    <form asp-area="Admin" asp-controller="Brand" asp-action="DeleteBrand" class="text-center">
        <input asp-for="Id" hidden />
        <button class="btn btn-success">بله <span class="bi bi-check2-circle fa-lg"></span></button>
        <a asp-area="Admin" asp-controller="Brand" asp-action="Index" class="btn btn-danger">خیر <span class=" bi bi-x-circle fa-lg"></span></a>
    </form>
</div>

Shopping/Areas/Admin/Views/Brand/EditBrand.cshtml
@model Shopping.Core.ViewModels.EditBrandViewModel

@{
    ViewData["Title"] = "EditBrand";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>EditBrand</h1>

<h4>Brand</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-area="Admin" asp-controller="Brand" asp-action="EditBrand" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="BrandEnName" class="control-label"></label>
                <input asp-for="BrandEnName" class="form-control" />
                <span asp-validation-for="BrandEnName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BrandFaName" class="control-label"></label>
                <input asp-for="BrandFaName" class="form-control" />
                <span asp-validation-for="BrandFaName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <br />
                <input type="file" name="File" onchange="ImgPreview(this)" accept=".jpg,.png" />
                <img id="Brand-preview" src="~/Images/Brand/@Model.BrandImg" width="256" />
                <label asp-for="BrandImg" class="control-label"></label>
                <input asp-for="BrandImg" value="@Model.BrandImg" id="img-name" class="form-control" />
                <span asp-validation-for="BrandImg" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BrandDes" class="control-label"></label>
                <input asp-for="BrandDes" class="form-control" />
                <span asp-validation-for="BrandDes" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="NotShow" /> @Html.DisplayNameFor(model => model.NotShow)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

<script>
    function ImgPreview(input) {
        if (input.files && input.files[0]) {
            let reader = new FileReader();
            reader.onload = (e) => {
                let img = document.getElementById('Brand-preview');
                img.setAttribute('src', e.target.result);

                document.getElementById('img-name').value = input.files[0].name;
            }

            reader.readAsDataURL(input.files[0]);
        }
    }
</script>

Shopping/Areas/Admin/Views/Brand/EditBrandTitel.cshtml
@model Shopping.Core.ViewModels.EditBrandViewModel

@{
    ViewData["Title"] = "EditBrand";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>EditBrand</h1>

<h4>Brand</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-area="Admin" asp-controller="Brand" asp-action="EditBrandTitel">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="BrandEnName" class="control-label"></label>
                <input asp-for="BrandEnName" class="form-control" />
                <span asp-validation-for="BrandEnName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BrandFaName" class="control-label"></label>
                <input asp-for="BrandFaName" class="form-control" />
                <span asp-validation-for="BrandFaName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BrandDes" class="control-label"></label>
                <input asp-for="BrandDes" class="form-control" />
                <span asp-validation-for="BrandDes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BrandImg" class="control-label" hidden></label>
                <input asp-for="BrandImg" class="form-control" readonly type="hidden"/>
                <img src="~/images/brand/@Model.BrandImg"/>
                <span asp-validation-for="BrandImg" class="text-danger" hidden></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="NotShow" /> @Html.DisplayNameFor(model => model.NotShow)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Shopping/Areas/Admin/Views/Brand/Index.cshtml
@model IEnumerable<Shopping.Database.Model.Brand>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-area="Admin" asp-controller="Brand" asp-action="CreateNewBrand" class="btn btn-success"><span class="bi bi-patch-plus"> Create</span></a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.BrandEnName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BrandFaName)
            </th>
            @* <th>
                @Html.DisplayNameFor(model => model.BrandDes)
            </th> *@
            <th>
                @Html.DisplayNameFor(model => model.BrandImg)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NotShow)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.BrandEnName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BrandFaName)
                </td>
               @*<td>
                    @Html.DisplayFor(modelItem => item.BrandDes)
                </td> *@
                <th>
                    @*  @Html.DisplayNameFor(model => model.BrandImg) *@
                    @{
                        if (item.BrandImg != null)
                        {
                            <img src="~/Images/Brand/@item.BrandImg" width="110">
                            
                        }
                        else
                        {
                            @Html.DisplayNameFor(model => model.BrandImg)
                        }
                        
                    }
                    
                </th>
                <td>
                    @Html.DisplayFor(modelItem => item.NotShow)
                </td>
                <td>
                    <a asp-area="Admin" asp-controller="Brand" asp-action="EditBrand" asp-route-BrandId="@item.Id" class="btn btn-warning"><span class="bi bi bi-pen"></span></a> |
                    <a asp-area="Admin" asp-controller="Brand" asp-action="BrandDetails" asp-route-BrandId="@item.Id" class="btn btn-info"><span class="bi bi-info-square"></span></a> |
                    <a data-bs-toggle="modal" data-bs-target="#exampleModal" onclick="DeleteBrand('@(item.Id)')" class="btn btn-danger"><span class="fa fa-trash-o"></span></a> |
                </td>
            </tr>
        }
    </tbody>
</table>


<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title text-center fs-5" id="exampleModalLabel">حذف کردن برند</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div id="modalBody" class="modal-body">
                ...
            </div>
            @*<div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Save changes</button>
            </div>*@
        </div>
    </div>
</div>



<script>
    const myModal = document.getElementById('myModal')
    const myInput = document.getElementById('myInput')

    myModal.addEventListener('shown.bs.modal', () => {
        myInput.focus()
    })
    function DeleteBrand(BrandId) {
        $.ajax({
            url: '/admin/Brand/DeleteBrand',
            type: 'get',
            data: {/*controller parameter*/  id: BrandId /*send parameter*/ },
            success: (result) => {
                document.getElementById('modalBody').innerHTML = result;
            }
        })
    }

</script>